### ISSUE TITLE
usage with babel?

### ISSUE THREAD

**Issue by psi-4ward** [johnsoftek/plugin-jade#12] opened 2015-12-30 19:39 UTC
Ive installed you Plugin and setup jspm with babel.

``` javascript
import tpl from 'dash.jade!';
console.log(tpl());
```

brings me
`GET http://127.0.0.1:8080/jspm_packages/npm/jade@1.11.0.js 404 (Not Found)`

Any ideas whats wrong here?

**Comment by johnsoftek** [comment] 2015-12-30 21:53
Closed as duplicate of #11.

**Closed as completed by johnsoftek** 2015-12-30 21:53 UTC
