### ISSUE TITLE
Error while using plugin on windows 

### ISSUE THREAD

**Issue by MaciejBaj** [johnsoftek/plugin-jade#4] opened 2015-02-23 15:43 UTC
In my project I wanted to use plugin-jade with jspm version 0.14.0. After 'jspm install', regarding to plugin-jade readme file I tried to build bundled script that uses your plugin. It fails. I am working on Windows 7. When I tried on Linux- it works.

Here is message from terminal:

```
D:\projects\maps\jspm_packages\github\johnsoftek\plugin-jade@0.4.0>jspm bundle app
Configuration file config.js doesn't exist, create it? [yes]:
     Building the bundle tree for app...

err  Error: Error loading "test.jade!jade" at <unknown>
     Error loading "test.jade!jade" from "app" at file:D:\projects\maps\jspm_packages\github\johnsoftek\plugin-jade@0.4.0/app.js
     Error loading "jade-compiler" at file:D:\projects\maps\jspm_packages\github\johnsoftek\plugin-jade@0.4.0/jade-compiler.js
     Error loading "jade-compiler" from "jade" at file:D:\projects\maps\jspm_packages\github\johnsoftek\plugin-jade@0.4.0/jade.js
     ENOENT, open 'D:\projects\maps\jspm_packages\github\johnsoftek\plugin-jade@0.4.0\jade-compiler.js'
```

**Comment by johnsoftek** [comment] 2015-02-23 22:37
I can't test this right now but try changing to D:\projects\maps before
"jspm bundle app"

**Comment by johnsoftek** [comment] 2015-02-24 10:03
@MaciejBaj I reproduced your error by running jspm bundle from the wrong directory. When you run jspm bundle, jspm expects the current directory to contain config.json, so you need to run jspm bundle from D:\projects\maps.

**Comment by MaciejBaj** [comment] 2015-03-05 15:04
now I am using runtime es6 compiler. The same error appears on browser logs.
![jspm path error](https://cloud.githubusercontent.com/assets/6909553/6507264/22d2a4ac-c351-11e4-915e-c9e2e9f372bf.PNG)

**Comment by johnsoftek** [comment] 2015-03-05 22:15
@guybedford Any ideas on this one? Looks like the full file path is being appended to the url.

**Comment by johnsoftek** [comment] 2015-03-05 22:49
@MaciejBaj What is your http server set up?

**Comment by guybedford** [comment] 2015-03-05 23:14
@MaciejBaj this looks like a bug from jspm-npm that was recently fixed. Try running `npm update jspm (-g if necessary) && jspm install -f`.

**Comment by capaj** [comment] 2015-06-16 12:48
@johnsoftek I think you can close this bug, as I have tested the plugin on windows and it works on windows with latests JSPM v 0.16.0. There are however other issues, which I've fixed and opened a PR.

**Comment by johnsoftek** [comment] 2015-06-16 14:17
@MaciejBaj Would you mind registering an issue for the PR?

Also, I would like to find a solution that does not require changing the code when the Jade version is updated. It should just be a config change.

**Closed as completed by johnsoftek** 2015-06-16 14:17 UTC

**Comment by MaciejBaj** [comment] 2015-06-17 14:24
I confirm, the problem is solved with latests JSPM and plugin-jade.
